layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jekyll-feed
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  # sort_by: pushed
  sort_by options:
    - pushed
    - stars
  limit: 6
  exclude:
    archived: true
    forks: true
    projects:

social_media:
  # instagram: your_username
  github: j4qfrost
  linkedin: anhquan-nguyen
  # mastodon: your_username
  # twitter: your_username
  # youtube: your_username

blogs:
  - name: Hello, Rox!
    url: j4qfrost.github.io/hello-rox

orgs:
  - name: Knights of the Funcitonal Calculus
    url: https://github.com/Knights-of-the-Functional-Calculus
  - name: Game Dev Studio UCSD
    url: https://github.com/GameDevStudioUCSD

feed:
  categories:
    - life
    - tech
    - anime
    - politics
    - misc

topics:
  - name: Rust
    web_url: https://github.com/topics/rust
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/rust/rust.png

  - name: Go
    web_url: https://github.com/topics/go
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/go/go.png

  - name: Python
    web_url: https://github.com/topics/python
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/python/python.png

  - name: Docker
    web_url: https://github.com/topics/docker
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/docker/docker.png
 
  - name: OpenGL
    web_url: https://github.com/topics/opengl
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/opengl/opengl.png

  - name: Awesome
    web_url: https://github.com/topics/awesome
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/awesome/awesome.png
